services:
  db_students:
    image: postgres 
    container_name: db_students
    restart: always 
    ports:
      - 2345:5432
    env_file:
      - .env 
    volumes:
      - vl_students:/var/lib/postgresql/data
  node_app:
    container_name: node_app
    build: . 
    ports:
      - 5000:5000
    depends_on:
      - db_students  
    env_file:
      - .env 
    volumes:
      vl_students: